### ISSUE TITLE
(TODO) - Incorporate second LongModel

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#80]
We should include a second longmodel in our initial release in order to help clarify the separation of code between child and parent classes (i.e. ExponentialLongModel vs LongModel). 

Recommendations for a second model to add include:

> In Yin-Guchelaar (2019), referring to Table 1, models in Eqs. 26 (SF), 28 (GSF) and 32 (CB) are the most commonly used ones for TGI.

We need to:

- [x] pick one of these models
- [ ] Add details to our statistical specification document
- [ ] Draft up the stan code to implement it
- [ ] Decide how to split the code between parent and child modules

This will be dependent on #66

**Comment by mercifr1** [comment]
As discussed, the model implemented so far is the GSF model (eq.28). 
GSF is a generalization of the SF model (eq.26).
It would be good to have these 3 models implemented in the package, in addition to the simple linear model (which can be used as an entry point from a model-building perspective).
If you point me to the document, I can add the model specifications accordingly.
Hope this helps
